package GameState;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.KeyEvent;
import java.util.ArrayList;

import GameElement.Beat;
import GameElement.EffectAnimation;
import GameElement.InterfaceBackground;
import GameElement.Note;
import GameElement.ResultBackground;
import GameEnvironment.Music;

//read GameAdrenaline for explanation
public class GameMariya extends GameState
                   implements Runnable {

	private InterfaceBackground bg;
	private Music gameMusic;
	private Beat[] beats = null;
	
	
	private ArrayList<Note> notes = new ArrayList<Note>();
	
	
	private Thread game;
	
	private int score;
	private int combo;
	
	private EffectAnimation effect;
	
	private int startTime;
	
	private boolean displayResult;
	private boolean showingResult;
	private ResultBackground rbg;
	
	private boolean exit;
	
	private Music beatSound;
	
	public GameMariya(GameStateManager gsm) {
		this.gsm = gsm;
		
		init();
	}
	
	@Override
	public void init() {
		
		score = 0; combo = 0;
		
		displayResult = false;
		showingResult = false;
		rbg = new ResultBackground();
		
		bg = new InterfaceBackground("/image/ThePlanIsSimple.jpg");
		
		setBeat();
		
		gameMusic = new Music("Mariya.mp3", false);
		gameMusic.start();
		
		effect = new EffectAnimation();
		
		game = new Thread(this);
		game.start();
		
		exit = false;
		
		
		beatSound = new Music("beat.mp3", false);
		
	}
	
	public void setBeat() {
		startTime = 1100; 
		int gap = (int)(60.0 / 360 * 1000);
		beats = new Beat[] {
				new Beat(startTime + gap * 1, "S"),
				new Beat(startTime + gap * 3, "D"),
				new Beat(startTime + gap * 5, "S"),
				new Beat(startTime + gap * 7, "D"),
				new Beat(startTime + gap * 9, "F"),
				new Beat(startTime + gap * 11, "Space"), 
				new Beat(startTime + gap * 18, "S"), 
				new Beat(startTime + gap * 19, "D"),
				new Beat(startTime + gap * 20, "F"),             
				new Beat(startTime + gap * 21, "D"),
				new Beat(startTime + gap * 22, "K"), 
				new Beat(startTime + gap * 25, "F"),
				new Beat(startTime + gap * 26, "K"),
				new Beat(startTime + gap * 29, "L"),
				new Beat(startTime + gap * 30, "L"),
				new Beat(startTime + gap * 32, "L"),  
				new Beat(startTime + gap * 36, "L"),
				new Beat(startTime + gap * 37, "J"),
				new Beat(startTime + gap * 38, "D"),
				new Beat(startTime + gap * 39, "S"),
				new Beat(startTime + gap * 40, "Space"), 
				new Beat(startTime + gap * 42, "D"),
				new Beat(startTime + gap * 44, "S"),
				new Beat(startTime + gap * 45, "D"),
				new Beat(startTime + gap * 47, "F"),
				new Beat(startTime + gap * 48, "F"),
				new Beat(startTime + gap * 51, "J"),
				new Beat(startTime + gap * 53, "L"), 
				new Beat(startTime + gap * 54, "S"), 
				new Beat(startTime + gap * 55, "D"),
				new Beat(startTime + gap * 56, "F"),              
				new Beat(startTime + gap * 57, "J"),
				new Beat(startTime + gap * 58, "K"),  
				new Beat(startTime + gap * 59, "L"),
				new Beat(startTime + gap * 60, "S"),  
				new Beat(startTime + gap * 61, "D"),
				new Beat(startTime + gap * 62, "F"), 
				new Beat(startTime + gap * 66, "S"), 
				new Beat(startTime + gap * 67, "D"),
				new Beat(startTime + gap * 70, "D"),
				new Beat(startTime + gap * 71, "D"),
				new Beat(startTime + gap * 72, "D"),
				new Beat(startTime + gap * 77, "S"),
				new Beat(startTime + gap * 78, "J"), 
				new Beat(startTime + gap * 79, "F"),             
				new Beat(startTime + gap * 80, "D"),
				new Beat(startTime + gap * 81, "S"), 
				new Beat(startTime + gap * 84, "S"),
				new Beat(startTime + gap * 85, "D"),
				new Beat(startTime + gap * 88, "S"),
				new Beat(startTime + gap * 89, "D"),
				new Beat(startTime + gap * 91, "S"),  
				new Beat(startTime + gap * 95, "S"),
				new Beat(startTime + gap * 96, "K"),
				new Beat(startTime + gap * 97, "F"),
				new Beat(startTime + gap * 98, "D"),
				new Beat(startTime + gap * 99, "S"), 
				new Beat(startTime + gap * 102, "F"),
				new Beat(startTime + gap * 103, "D"),
				new Beat(startTime + gap * 106, "S"),
				new Beat(startTime + gap * 107, "D"),
				new Beat(startTime + gap * 109, "F"), 
				new Beat(startTime + gap * 110, "D"),
				new Beat(startTime + gap * 111, "J"), 
				new Beat(startTime + gap * 112, "S"), 
				new Beat(startTime + gap * 113, "S"),
				new Beat(startTime + gap * 114, "D"),              
				new Beat(startTime + gap * 115, "J"),
				new Beat(startTime + gap * 116, "K"),  
				new Beat(startTime + gap * 117, "L"),
				new Beat(startTime + gap * 118, "D"), 
				new Beat(startTime + gap * 119, "K"),
				new Beat(startTime + gap * 120, "L"), 
				new Beat(startTime + gap * 123, "Space"), 
				new Beat(startTime + gap * 124, "Space"),
				new Beat(startTime + gap * 125, "Space"),
				new Beat(startTime + gap * 126, "Space"), 
				new Beat(startTime + gap * 128, "F"),
				new Beat(startTime + gap * 129, "D"),
				new Beat(startTime + gap * 130, "F"), 
				new Beat(startTime + gap * 131, "K"), 
				new Beat(startTime + gap * 132, "K"), 
				new Beat(startTime + gap * 134, "D"),
				new Beat(startTime + gap * 135, "S"),              
				new Beat(startTime + gap * 136, "D"),
				new Beat(startTime + gap * 137, "F"),  
				new Beat(startTime + gap * 138, "D"), 
				new Beat(startTime + gap * 140, "K"), 
				new Beat(startTime + gap * 141, "J"),
				new Beat(startTime + gap * 142, "K"), 
				new Beat(startTime + gap * 143, "Space"),
				new Beat(startTime + gap * 144, "Space"),
				new Beat(startTime + gap * 145, "L"),
				new Beat(startTime + gap * 146, "D"),
				new Beat(startTime + gap * 147, "F"),
				new Beat(startTime + gap * 148, "F"),
				new Beat(startTime + gap * 150, "F"), 
				new Beat(startTime + gap * 151, "S"), 
				new Beat(startTime + gap * 152, "D"),
				new Beat(startTime + gap * 153, "F"),             
				new Beat(startTime + gap * 154, "D"),
				new Beat(startTime + gap * 155, "S"), 
				new Beat(startTime + gap * 156, "F"),
				new Beat(startTime + gap * 157, "K"),
				new Beat(startTime + gap * 158, "L"),
				new Beat(startTime + gap * 159, "L"),
				new Beat(startTime + gap * 161, "L"),
				new Beat(startTime + gap * 162, "K"),
				new Beat(startTime + gap * 163, "J"),
				new Beat(startTime + gap * 164, "D"),
				new Beat(startTime + gap * 165, "S"),
				new Beat(startTime + gap * 166, "Space"), 
				new Beat(startTime + gap * 168, "D"),
				new Beat(startTime + gap * 170, "S"),
				new Beat(startTime + gap * 171, "D"),
				new Beat(startTime + gap * 173, "F"),
				new Beat(startTime + gap * 174, "F"),
				new Beat(startTime + gap * 177, "J"),
				new Beat(startTime + gap * 179, "L"), 
				new Beat(startTime + gap * 180, "S"), 
				new Beat(startTime + gap * 181, "D"),
				new Beat(startTime + gap * 182, "F"),              
				new Beat(startTime + gap * 183, "J"),
				new Beat(startTime + gap * 184, "K"),  
				new Beat(startTime + gap * 185, "L"),
				new Beat(startTime + gap * 186, "S"),  
				new Beat(startTime + gap * 187, "D"),
				new Beat(startTime + gap * 188, "F"), 
				new Beat(startTime + gap * 192, "S"), 
				new Beat(startTime + gap * 193, "D"),
				new Beat(startTime + gap * 196, "D"),
				new Beat(startTime + gap * 197, "D"),
				new Beat(startTime + gap * 198, "D"),
				new Beat(startTime + gap * 203, "S"),
				new Beat(startTime + gap * 204, "J"), 
				new Beat(startTime + gap * 205, "F"),             
				new Beat(startTime + gap * 206, "D"),
				new Beat(startTime + gap * 207, "S"), 
				new Beat(startTime + gap * 210, "S"),
				new Beat(startTime + gap * 211, "D"),
				new Beat(startTime + gap * 214, "S"),
				new Beat(startTime + gap * 215, "D"),
				new Beat(startTime + gap * 217, "S"),  
				new Beat(startTime + gap * 218, "S"),
				new Beat(startTime + gap * 219, "K"),
				new Beat(startTime + gap * 220, "F"),
				new Beat(startTime + gap * 221, "D"),
				new Beat(startTime + gap * 222, "S"), 
				new Beat(startTime + gap * 224, "F"),
				new Beat(startTime + gap * 225, "D"),
				new Beat(startTime + gap * 226, "S"),
				new Beat(startTime + gap * 227, "D"),
				new Beat(startTime + gap * 229, "F"), 
				new Beat(startTime + gap * 230, "D"),
				new Beat(startTime + gap * 231, "J"), 
				new Beat(startTime + gap * 232, "S"), 
				new Beat(startTime + gap * 233, "S"),
				new Beat(startTime + gap * 234, "D"),              
				new Beat(startTime + gap * 235, "J"),
				new Beat(startTime + gap * 236, "K"),  
				new Beat(startTime + gap * 237, "L"),
				new Beat(startTime + gap * 238, "D"), 
				new Beat(startTime + gap * 239, "K"),
				new Beat(startTime + gap * 240, "L"), 
				new Beat(startTime + gap * 241, "Space"), 
				new Beat(startTime + gap * 242, "Space"),
				new Beat(startTime + gap * 242, "Space"),
				new Beat(startTime + gap * 243, "Space"), 
				new Beat(startTime + gap * 244, "F"),
				new Beat(startTime + gap * 245, "D"),
				new Beat(startTime + gap * 246, "F"), 
				new Beat(startTime + gap * 247, "K"), 
				new Beat(startTime + gap * 248, "K"), 
				new Beat(startTime + gap * 250, "D"),
				new Beat(startTime + gap * 251, "S"),              
				new Beat(startTime + gap * 252, "D"),
				new Beat(startTime + gap * 253, "F"),  
				new Beat(startTime + gap * 254, "D"), 
				new Beat(startTime + gap * 255, "K"), 
				new Beat(startTime + gap * 256, "J"),
				new Beat(startTime + gap * 257, "K"), 
				new Beat(startTime + gap * 258, "Space"),
				new Beat(startTime + gap * 259, "J"),
				new Beat(startTime + gap * 260, "K"),  
				new Beat(startTime + gap * 261, "L"),
				new Beat(startTime + gap * 262, "S"),  
				new Beat(startTime + gap * 263, "D"),
				new Beat(startTime + gap * 264, "F"), 
				new Beat(startTime + gap * 268, "S"), 
				new Beat(startTime + gap * 269, "D"),
				new Beat(startTime + gap * 270, "D"),
				new Beat(startTime + gap * 271, "D"),
				new Beat(startTime + gap * 272, "D"),
				new Beat(startTime + gap * 273, "S"),
				new Beat(startTime + gap * 274, "J"), 
				new Beat(startTime + gap * 275, "F"),             
				new Beat(startTime + gap * 276, "D"),
				new Beat(startTime + gap * 278, "S"), 
				new Beat(startTime + gap * 279, "S"),
				new Beat(startTime + gap * 280, "D"),
				new Beat(startTime + gap * 281, "S"),
				new Beat(startTime + gap * 282, "D"),
				new Beat(startTime + gap * 283, "S"),  
				new Beat(startTime + gap * 284, "S"),
				new Beat(startTime + gap * 285, "K"),
				new Beat(startTime + gap * 286, "F"),
				new Beat(startTime + gap * 287, "D"),
				new Beat(startTime + gap * 288, "S"), 
				new Beat(startTime + gap * 289, "F"),
				new Beat(startTime + gap * 290, "D"),
				new Beat(startTime + gap * 291, "S"),
				new Beat(startTime + gap * 292, "D"),
				new Beat(startTime + gap * 293, "F"), 
				new Beat(startTime + gap * 294, "D"),
				new Beat(startTime + gap * 295, "J"), 
				new Beat(startTime + gap * 296, "S"), 
				new Beat(startTime + gap * 297, "S"),
				new Beat(startTime + gap * 298, "D"),              
				new Beat(startTime + gap * 299, "J"),
				new Beat(startTime + gap * 300, "K"),  
				new Beat(startTime + gap * 301, "L"),
				new Beat(startTime + gap * 302, "D"), 
				new Beat(startTime + gap * 303, "K"),
				new Beat(startTime + gap * 304, "L"), 
				new Beat(startTime + gap * 305, "Space"), 
				new Beat(startTime + gap * 306, "Space"),
				new Beat(startTime + gap * 307, "Space"),
				new Beat(startTime + gap * 308, "Space"), 
				new Beat(startTime + gap * 309, "F"),
				new Beat(startTime + gap * 310, "D"),
				new Beat(startTime + gap * 311, "F"), 
				new Beat(startTime + gap * 312, "K"), 
				new Beat(startTime + gap * 313, "K"), 
				new Beat(startTime + gap * 314, "D"),
				new Beat(startTime + gap * 315, "S"),              
				new Beat(startTime + gap * 316, "D"),
				new Beat(startTime + gap * 317, "F"),  
				new Beat(startTime + gap * 318, "D"), 
				new Beat(startTime + gap * 319, "K"), 
				new Beat(startTime + gap * 320, "J"),
				new Beat(startTime + gap * 321, "K"), 
				new Beat(startTime + gap * 322, "Space"),
				new Beat(startTime + gap * 323, "F"), 
				new Beat(startTime + gap * 325, "S"), 
				new Beat(startTime + gap * 326, "D"),
				new Beat(startTime + gap * 329, "D"),
				new Beat(startTime + gap * 330, "D"),
				new Beat(startTime + gap * 331, "D"),
				new Beat(startTime + gap * 336, "S"),
				new Beat(startTime + gap * 337, "J"), 
				new Beat(startTime + gap * 338, "F"),             
				new Beat(startTime + gap * 339, "D"),
				new Beat(startTime + gap * 340, "S"), 
				new Beat(startTime + gap * 343, "S"),
				new Beat(startTime + gap * 344, "D"),
				new Beat(startTime + gap * 348, "S"),
				new Beat(startTime + gap * 349, "D"),
				new Beat(startTime + gap * 350, "S"),  
				new Beat(startTime + gap * 344, "S"),
				new Beat(startTime + gap * 346, "K"),
				new Beat(startTime + gap * 347, "F"),
				new Beat(startTime + gap * 348, "D"),
				new Beat(startTime + gap * 349, "S"), 
				new Beat(startTime + gap * 350, "F"),
				new Beat(startTime + gap * 352, "D"),
				new Beat(startTime + gap * 353, "S"),
				new Beat(startTime + gap * 357, "D"),
				new Beat(startTime + gap * 358, "F"), 
				new Beat(startTime + gap * 359, "D"),
				new Beat(startTime + gap * 360, "J"), 
				new Beat(startTime + gap * 361, "S"), 
				new Beat(startTime + gap * 362, "S"),
				new Beat(startTime + gap * 363, "D"),              
				new Beat(startTime + gap * 364, "J"),
				new Beat(startTime + gap * 365, "K"),  
				new Beat(startTime + gap * 366, "L"),
				new Beat(startTime + gap * 367, "D"), 
				new Beat(startTime + gap * 368, "K"),
				new Beat(startTime + gap * 369, "L"), 
				new Beat(startTime + gap * 370, "Space"), 
				new Beat(startTime + gap * 371, "L"),
				new Beat(startTime + gap * 373, "L"),  
				new Beat(startTime + gap * 374, "K"),
				new Beat(startTime + gap * 375, "J"),
				new Beat(startTime + gap * 376, "D"),
				new Beat(startTime + gap * 377, "S"),
				new Beat(startTime + gap * 378, "Space"), 
				new Beat(startTime + gap * 380, "D"),
				new Beat(startTime + gap * 382, "S"),
				new Beat(startTime + gap * 383, "D"),
				new Beat(startTime + gap * 384, "F"),
				new Beat(startTime + gap * 385, "F"),
				new Beat(startTime + gap * 386, "J"),
				new Beat(startTime + gap * 388, "L"), 
				new Beat(startTime + gap * 389, "S"), 
				new Beat(startTime + gap * 390, "D"),
				new Beat(startTime + gap * 391, "F"),              
				new Beat(startTime + gap * 392, "J"),
				new Beat(startTime + gap * 393, "K"),  
				new Beat(startTime + gap * 394, "L"),
				new Beat(startTime + gap * 395, "S"),  
				new Beat(startTime + gap * 396, "D"),
				new Beat(startTime + gap * 397, "F"),
				new Beat(startTime + gap * 401, "S"), 
				new Beat(startTime + gap * 402, "D"),
				new Beat(startTime + gap * 406, "D"),
				new Beat(startTime + gap * 407, "D"),
				new Beat(startTime + gap * 408, "D"),
				new Beat(startTime + gap * 413, "S"),
				new Beat(startTime + gap * 414, "J"), 
				new Beat(startTime + gap * 415, "F"),             
				new Beat(startTime + gap * 416, "D"),
				new Beat(startTime + gap * 417, "S"), 
				new Beat(startTime + gap * 418, "S"),
				new Beat(startTime + gap * 419, "D"),
				new Beat(startTime + gap * 422, "S"),
				new Beat(startTime + gap * 423, "D"),
				new Beat(startTime + gap * 425, "S"),  
				new Beat(startTime + gap * 429, "S"),
				new Beat(startTime + gap * 430, "K"),
				new Beat(startTime + gap * 431, "F"),
				new Beat(startTime + gap * 432, "D"),
				new Beat(startTime + gap * 433, "S"), 
				new Beat(startTime + gap * 434, "F"),
				new Beat(startTime + gap * 435, "D"),
				new Beat(startTime + gap * 436, "S"),
				new Beat(startTime + gap * 437, "D"),
				new Beat(startTime + gap * 439, "F"), 
				new Beat(startTime + gap * 440, "D"),
				new Beat(startTime + gap * 441, "J"), 
				new Beat(startTime + gap * 442, "S"), 
				new Beat(startTime + gap * 443, "S"),
				new Beat(startTime + gap * 444, "D"),              
				new Beat(startTime + gap * 445, "J"),
				new Beat(startTime + gap * 446, "K"), 
				new Beat(startTime + gap * 447, "D"),
				new Beat(startTime + gap * 448, "D"),
				new Beat(startTime + gap * 453, "S"),
				new Beat(startTime + gap * 454, "J"), 
				new Beat(startTime + gap * 455, "F"),             
				new Beat(startTime + gap * 456, "D"),
				new Beat(startTime + gap * 457, "S"), 
				new Beat(startTime + gap * 460, "S"),
				new Beat(startTime + gap * 461, "D"),
				new Beat(startTime + gap * 465, "S"),
				new Beat(startTime + gap * 466, "D"),
				new Beat(startTime + gap * 467, "S"),  
				new Beat(startTime + gap * 468, "S"),
				new Beat(startTime + gap * 469, "K"),
				new Beat(startTime + gap * 470, "F"),
				new Beat(startTime + gap * 471, "D"),
				new Beat(startTime + gap * 472, "S"), 
				new Beat(startTime + gap * 473, "F"),
				new Beat(startTime + gap * 474, "D"),
				new Beat(startTime + gap * 475, "S"),
				new Beat(startTime + gap * 476, "D"),
				new Beat(startTime + gap * 477, "F"), 
				new Beat(startTime + gap * 478, "D"),
				new Beat(startTime + gap * 479, "J"), 
				new Beat(startTime + gap * 480, "S"), 
				new Beat(startTime + gap * 481, "S"),
				new Beat(startTime + gap * 482, "D"),              
				new Beat(startTime + gap * 483, "J"),
				new Beat(startTime + gap * 484, "K"),  
				new Beat(startTime + gap * 485, "L"),
				new Beat(startTime + gap * 486, "D"), 
				new Beat(startTime + gap * 487, "K"),
				new Beat(startTime + gap * 488, "L"), 
				new Beat(startTime + gap * 490, "Space"), 
				new Beat(startTime + gap * 491, "D"), 
				new Beat(startTime + gap * 492, "K"),
				new Beat(startTime + gap * 493, "L"), 
				new Beat(startTime + gap * 494, "Space"),
				new Beat(startTime + gap * 495, "Space"),
				new Beat(startTime + gap * 496, "Space"),
				new Beat(startTime + gap * 497, "Space"),
				new Beat(startTime + gap * 498, "S"), 
				new Beat(startTime + gap * 500, "F"),
				new Beat(startTime + gap * 501, "D"),
				new Beat(startTime + gap * 502, "S"),
				new Beat(startTime + gap * 505, "D"),
				new Beat(startTime + gap * 506, "F"), 
				new Beat(startTime + gap * 507, "D"),
				new Beat(startTime + gap * 508, "J"), 
				new Beat(startTime + gap * 509, "S"), 
				new Beat(startTime + gap * 511, "S"),
				new Beat(startTime + gap * 512, "D"),              
				new Beat(startTime + gap * 513, "J"),
				new Beat(startTime + gap * 514, "K"),  
				new Beat(startTime + gap * 515, "L"),
				new Beat(startTime + gap * 516, "D"), 
				new Beat(startTime + gap * 517, "K"),
				new Beat(startTime + gap * 518, "L"), 
				new Beat(startTime + gap * 519, "Space"), 
				new Beat(startTime + gap * 520, "L"),
				new Beat(startTime + gap * 522, "L"),  
				new Beat(startTime + gap * 523, "K"),
				new Beat(startTime + gap * 524, "J"),
				new Beat(startTime + gap * 524, "D"),
				new Beat(startTime + gap * 524, "S"),
				new Beat(startTime + gap * 525, "Space"), 
				new Beat(startTime + gap * 527, "D"),
				new Beat(startTime + gap * 529, "S"),
				new Beat(startTime + gap * 530, "D"),
				new Beat(startTime + gap * 531, "L"), 
				new Beat(startTime + gap * 533, "Space"), 
				new Beat(startTime + gap * 534, "Space"),
				new Beat(startTime + gap * 535, "Space"),
				new Beat(startTime + gap * 536, "Space"), 
				new Beat(startTime + gap * 537, "F"),
				new Beat(startTime + gap * 538, "D"),
				new Beat(startTime + gap * 539, "F"), 
				new Beat(startTime + gap * 540, "K"), 
				new Beat(startTime + gap * 542, "D"),
				new Beat(startTime + gap * 543, "S"),              
				new Beat(startTime + gap * 544, "D"),
				new Beat(startTime + gap * 545, "F"),  
				new Beat(startTime + gap * 546, "D"), 
				new Beat(startTime + gap * 548, "K"), 
				new Beat(startTime + gap * 549, "J"),
				new Beat(startTime + gap * 550, "K"), 
				new Beat(startTime + gap * 552, "Space"),
				new Beat(startTime + gap * 554, "Space"),
				new Beat(startTime + gap * 555, "L"),
				new Beat(startTime + gap * 556, "D"),
				new Beat(startTime + gap * 557, "F"),
				new Beat(startTime + gap * 558, "F"),
				new Beat(startTime + gap * 560, "F"), 
				new Beat(startTime + gap * 562, "S"), 
				new Beat(startTime + gap * 564, "D"),
				new Beat(startTime + gap * 565, "F"),             
				new Beat(startTime + gap * 568, "D"),
				new Beat(startTime + gap * 570, "S"), 
				new Beat(startTime + gap * 572, "F"),
				new Beat(startTime + gap * 572, "K"),
				new Beat(startTime + gap * 574, "L"),
				new Beat(startTime + gap * 575, "L"),
				new Beat(startTime + gap * 576, "L"),
				new Beat(startTime + gap * 577, "K"),
				new Beat(startTime + gap * 578, "J"),
				new Beat(startTime + gap * 580, "D"),
				new Beat(startTime + gap * 585, "S"),
				new Beat(startTime + gap * 586, "Space"), 
				new Beat(startTime + gap * 587, "D"),
				new Beat(startTime + gap * 588, "S"),
				new Beat(startTime + gap * 589, "D"),
				new Beat(startTime + gap * 591, "F"),
				new Beat(startTime + gap * 593, "F"),
				new Beat(startTime + gap * 595, "J"),
				new Beat(startTime + gap * 596, "L"), 
				new Beat(startTime + gap * 597, "S"), 
				new Beat(startTime + gap * 598, "D"),
				new Beat(startTime + gap * 599, "F"),              
				new Beat(startTime + gap * 600, "J"),
				new Beat(startTime + gap * 601, "K"),  
				new Beat(startTime + gap * 604, "L"),
				new Beat(startTime + gap * 608, "S"),  
				new Beat(startTime + gap * 610, "D"),
				new Beat(startTime + gap * 612, "F"), 
				new Beat(startTime + gap * 613, "S"), 
				new Beat(startTime + gap * 615, "D"),
				new Beat(startTime + gap * 617, "D"),
				new Beat(startTime + gap * 618, "D"),
				new Beat(startTime + gap * 619, "D"),
				new Beat(startTime + gap * 620, "S"),
				new Beat(startTime + gap * 621, "D"),
				new Beat(startTime + gap * 622, "S"),
				new Beat(startTime + gap * 624, "Space"), 
				new Beat(startTime + gap * 625, "D"),
				new Beat(startTime + gap * 627, "S"),
				new Beat(startTime + gap * 627, "D"),
				new Beat(startTime + gap * 630, "F"),
				new Beat(startTime + gap * 632, "F"),
				new Beat(startTime + gap * 633, "J"),
				new Beat(startTime + gap * 634, "L"), 
				new Beat(startTime + gap * 635, "S"), 
				new Beat(startTime + gap * 636, "D"),
				new Beat(startTime + gap * 637, "F"),              
				new Beat(startTime + gap * 638, "J"),
				new Beat(startTime + gap * 639, "K"),  
				new Beat(startTime + gap * 640, "L"),
				new Beat(startTime + gap * 641, "S"),  
				new Beat(startTime + gap * 642, "D"),
				new Beat(startTime + gap * 643, "F"), 
				new Beat(startTime + gap * 644, "S"), 
				new Beat(startTime + gap * 645, "D"),
				new Beat(startTime + gap * 646, "D"),
				new Beat(startTime + gap * 647, "D"),
				new Beat(startTime + gap * 648, "D"),
				new Beat(startTime + gap * 649, "S"),
				new Beat(startTime + gap * 650, "D"),
				new Beat(startTime + gap * 652, "D"),
				new Beat(startTime + gap * 654, "D"),
				new Beat(startTime + gap * 655, "S"),
				new Beat(startTime + gap * 657, "D"),
				new Beat(startTime + gap * 658, "S"),
				new Beat(startTime + gap * 659, "Space"), 
				new Beat(startTime + gap * 660, "D"),
				new Beat(startTime + gap * 662, "S"),
				new Beat(startTime + gap * 663, "D"),
				new Beat(startTime + gap * 664, "F"),
				new Beat(startTime + gap * 665, "F"),
				new Beat(startTime + gap * 667, "J"),
				new Beat(startTime + gap * 668, "L"), 
				new Beat(startTime + gap * 669, "S"), 
				new Beat(startTime + gap * 670, "D"),
				new Beat(startTime + gap * 671, "F"),              
				new Beat(startTime + gap * 672, "J"),
				new Beat(startTime + gap * 673, "K"),  
				new Beat(startTime + gap * 675, "L"),
				new Beat(startTime + gap * 677, "S"),  
				new Beat(startTime + gap * 678, "D"),
				new Beat(startTime + gap * 680, "F"), 
				new Beat(startTime + gap * 682, "S"), 
				new Beat(startTime + gap * 683, "D"),
				new Beat(startTime + gap * 684, "D"),
				new Beat(startTime + gap * 685, "D"),
				new Beat(startTime + gap * 687, "D"),
				new Beat(startTime + gap * 688, "S"),
				new Beat(startTime + gap * 689, "F"),              
				new Beat(startTime + gap * 690, "J"),
				new Beat(startTime + gap * 691, "K"),  
				new Beat(startTime + gap * 692, "L"),
				new Beat(startTime + gap * 693, "S"),  
				new Beat(startTime + gap * 694, "D"),
				new Beat(startTime + gap * 697, "F"), 
				new Beat(startTime + gap * 699, "S"), 
				new Beat(startTime + gap * 700, "D"),
				new Beat(startTime + gap * 701, "D"),
				new Beat(startTime + gap * 706, "D"),
				new Beat(startTime + gap * 707, "D"),
				new Beat(startTime + gap * 708, "S"),
				new Beat(startTime + gap * 710, "J"), 
				new Beat(startTime + gap * 712, "F"),             
				new Beat(startTime + gap * 714, "D"),
				new Beat(startTime + gap * 715, "S"), 
				new Beat(startTime + gap * 717, "S"),
				new Beat(startTime + gap * 719, "D"),
				new Beat(startTime + gap * 721, "S"),
				new Beat(startTime + gap * 723, "D"),
				new Beat(startTime + gap * 725, "S"),  
				new Beat(startTime + gap * 726, "S"),
				new Beat(startTime + gap * 727, "K"),
				new Beat(startTime + gap * 729, "F"),
				new Beat(startTime + gap * 730, "D"),
				new Beat(startTime + gap * 731, "S"), 
				new Beat(startTime + gap * 734, "F"),
				new Beat(startTime + gap * 735, "D"),
				new Beat(startTime + gap * 737, "S"),
				new Beat(startTime + gap * 738, "D"),
				new Beat(startTime + gap * 740, "F"), 
				new Beat(startTime + gap * 742, "D"),
				new Beat(startTime + gap * 743, "J"), 
				new Beat(startTime + gap * 745, "S"), 
				new Beat(startTime + gap * 747, "S"),
				new Beat(startTime + gap * 750, "D"),              
				new Beat(startTime + gap * 752, "J"),
				new Beat(startTime + gap * 753, "K"),  
				new Beat(startTime + gap * 755, "L"),
				new Beat(startTime + gap * 756, "D"), 
				new Beat(startTime + gap * 757, "K"),
				new Beat(startTime + gap * 759, "L"), 
				new Beat(startTime + gap * 761, "Space"), 
				new Beat(startTime + gap * 762, "Space"),
				new Beat(startTime + gap * 763, "Space"),
				new Beat(startTime + gap * 764, "Space"), 
				new Beat(startTime + gap * 765, "F"),
				new Beat(startTime + gap * 767, "D"),
				new Beat(startTime + gap * 768, "F"), 
				new Beat(startTime + gap * 770, "K"), 
				new Beat(startTime + gap * 772, "K"), 
				new Beat(startTime + gap * 773, "D"),
				new Beat(startTime + gap * 775, "S"),              
				new Beat(startTime + gap * 777, "D"),
				new Beat(startTime + gap * 778, "F"),  
				new Beat(startTime + gap * 779, "D"), 
				new Beat(startTime + gap * 784, "K"), 
				new Beat(startTime + gap * 788, "J"),
				new Beat(startTime + gap * 790, "K"), 
				new Beat(startTime + gap * 792, "Space"),
				new Beat(startTime + gap * 793, "Space"),
				new Beat(startTime + gap * 794, "L"),
				new Beat(startTime + gap * 795, "D"),
				new Beat(startTime + gap * 796, "F"),
				new Beat(startTime + gap * 797, "F"),
				new Beat(startTime + gap * 798, "F"), 
				new Beat(startTime + gap * 800, "S"), 
				new Beat(startTime + gap * 803, "D"),
				new Beat(startTime + gap * 804, "F"),             
				new Beat(startTime + gap * 805, "D"),
				new Beat(startTime + gap * 806, "D"),
				new Beat(startTime + gap * 807, "J"), 
				new Beat(startTime + gap * 808, "S"), 
				new Beat(startTime + gap * 809, "S"),
				new Beat(startTime + gap * 810, "D"),              
				new Beat(startTime + gap * 815, "J"),
				new Beat(startTime + gap * 820, "K"),  
				new Beat(startTime + gap * 827, "L"),
				new Beat(startTime + gap * 828, "D"), 
				new Beat(startTime + gap * 829, "K"),
				new Beat(startTime + gap * 830, "L"), 
				new Beat(startTime + gap * 832, "Space"), 
				new Beat(startTime + gap * 833, "Space"),
				new Beat(startTime + gap * 834, "Space"),
				new Beat(startTime + gap * 835, "Space"), 
				new Beat(startTime + gap * 837, "F"),
				new Beat(startTime + gap * 838, "D"),
				new Beat(startTime + gap * 840, "F"), 
				new Beat(startTime + gap * 841, "K"), 
				new Beat(startTime + gap * 842, "K"), 
				new Beat(startTime + gap * 843, "D"),
				new Beat(startTime + gap * 844, "S"),              
				new Beat(startTime + gap * 846, "D"),
				new Beat(startTime + gap * 847, "F"),  
				new Beat(startTime + gap * 848, "D"), 
				new Beat(startTime + gap * 850, "K"), 
				new Beat(startTime + gap * 851, "J"),
				new Beat(startTime + gap * 852, "K"), 
				new Beat(startTime + gap * 854, "Space"),
				new Beat(startTime + gap * 855, "Space"),
				new Beat(startTime + gap * 856, "L"),
				new Beat(startTime + gap * 858, "D"),
				new Beat(startTime + gap * 860, "F"),
				new Beat(startTime + gap * 861, "F"),
				new Beat(startTime + gap * 863, "F"), 
				new Beat(startTime + gap * 864, "S"), 
				new Beat(startTime + gap * 865, "D"),
				new Beat(startTime + gap * 867, "F"),
				new Beat(startTime + gap * 868, "L"),  
				new Beat(startTime + gap * 870, "L"),
				new Beat(startTime + gap * 871, "J"),
				new Beat(startTime + gap * 873, "D"),
				new Beat(startTime + gap * 875, "S"),
				new Beat(startTime + gap * 876, "Space"), 
				new Beat(startTime + gap * 877, "D"),
				new Beat(startTime + gap * 878, "S"),
				new Beat(startTime + gap * 880, "D"),
				new Beat(startTime + gap * 881, "F"),
				new Beat(startTime + gap * 883, "F"),
				new Beat(startTime + gap * 884, "J"),
				new Beat(startTime + gap * 885, "L"), 
				new Beat(startTime + gap * 886, "S"), 
				new Beat(startTime + gap * 887, "D"),
				new Beat(startTime + gap * 888, "F"),              
				new Beat(startTime + gap * 889, "J"),
				new Beat(startTime + gap * 890, "K"),  
				new Beat(startTime + gap * 891, "L"),
				new Beat(startTime + gap * 900, "S"),  
				new Beat(startTime + gap * 901, "D"),
				new Beat(startTime + gap * 902, "F"), 
				new Beat(startTime + gap * 906, "S"), 
				new Beat(startTime + gap * 907, "D"),
				new Beat(startTime + gap * 910, "D"),
				new Beat(startTime + gap * 911, "D"),
				new Beat(startTime + gap * 912, "D"),
				new Beat(startTime + gap * 917, "S"),
				new Beat(startTime + gap * 918, "J"), 
				new Beat(startTime + gap * 919, "F"),             
				new Beat(startTime + gap * 920, "D"),
				new Beat(startTime + gap * 921, "S"), 
				new Beat(startTime + gap * 924, "S"),
				new Beat(startTime + gap * 925, "D"),
				new Beat(startTime + gap * 928, "S"),
				new Beat(startTime + gap * 929, "D"),
				new Beat(startTime + gap * 931, "S"),  
				new Beat(startTime + gap * 933, "S"),
				new Beat(startTime + gap * 934, "K"),
				new Beat(startTime + gap * 935, "F"),
				new Beat(startTime + gap * 936, "D"),
				new Beat(startTime + gap * 937, "S"), 
				new Beat(startTime + gap * 940, "F"),
				new Beat(startTime + gap * 941, "D"),
				new Beat(startTime + gap * 944, "S"),
				new Beat(startTime + gap * 945, "D"),
				new Beat(startTime + gap * 947, "F"), 
				new Beat(startTime + gap * 948, "D"),
				new Beat(startTime + gap * 949, "J"), 
				new Beat(startTime + gap * 950, "S"), 
				new Beat(startTime + gap * 952, "S"),
				new Beat(startTime + gap * 953, "D"),              
				new Beat(startTime + gap * 954, "J"),
				new Beat(startTime + gap * 955, "K"),  
				new Beat(startTime + gap * 956, "L"),
				new Beat(startTime + gap * 957, "D"), 
				new Beat(startTime + gap * 958, "K"),
				new Beat(startTime + gap * 959, "L"), 
				new Beat(startTime + gap * 960, "Space"), 
				new Beat(startTime + gap * 961, "Space"),
				new Beat(startTime + gap * 962, "Space"),
				new Beat(startTime + gap * 963, "Space"), 
				new Beat(startTime + gap * 964, "F"),
				new Beat(startTime + gap * 965, "D"),
				new Beat(startTime + gap * 966, "F"), 
				new Beat(startTime + gap * 967, "K"), 
				new Beat(startTime + gap * 968, "K"), 
				new Beat(startTime + gap * 969, "D"),
				new Beat(startTime + gap * 970, "S"),              
				new Beat(startTime + gap * 971, "D"),
				new Beat(startTime + gap * 971, "F"),  
				new Beat(startTime + gap * 972, "D"), 
				new Beat(startTime + gap * 973, "K"), 
				new Beat(startTime + gap * 973, "J"),
				new Beat(startTime + gap * 975, "K"), 
				new Beat(startTime + gap * 976, "Space"),
				new Beat(startTime + gap * 977, "Space"),
				new Beat(startTime + gap * 978, "L"),
				new Beat(startTime + gap * 979, "D"),
				new Beat(startTime + gap * 979, "F"),
				new Beat(startTime + gap * 980, "F"),
				new Beat(startTime + gap * 982, "Space"), 
				new Beat(startTime + gap * 984, "S"), 
				new Beat(startTime + gap * 984, "D"),
				new Beat(startTime + gap * 984, "F"),             
				new Beat(startTime + gap * 986, "D"),
				new Beat(startTime + gap * 987, "S"), 
				new Beat(startTime + gap * 988, "F"),
				new Beat(startTime + gap * 989, "K"),
				new Beat(startTime + gap * 991, "L"),
				new Beat(startTime + gap * 992, "L"),
				new Beat(startTime + gap * 993, "L"),
				new Beat(startTime + gap * 994, "K"),
				new Beat(startTime + gap * 995, "J"),
				new Beat(startTime + gap * 996, "D"),
				new Beat(startTime + gap * 997, "S"),
				new Beat(startTime + gap * 998, "Space"), 
				new Beat(startTime + gap * 999, "D"),
				new Beat(startTime + gap * 1000, "S"),
				new Beat(startTime + gap * 1001, "D"),
				new Beat(startTime + gap * 1003, "F"),
				new Beat(startTime + gap * 1004, "F"),
				new Beat(startTime + gap * 1007, "J"),
				new Beat(startTime + gap * 1009, "L"), 
				new Beat(startTime + gap * 1010, "S"), 
				new Beat(startTime + gap * 1011, "D"),
				new Beat(startTime + gap * 1012, "F"),              
				new Beat(startTime + gap * 1013, "J"),
				new Beat(startTime + gap * 1014, "K"),  
				new Beat(startTime + gap * 1015, "L"),
				new Beat(startTime + gap * 1016, "S"),  
				new Beat(startTime + gap * 1017, "D"),
				new Beat(startTime + gap * 1018, "F"), 
				new Beat(startTime + gap * 1022, "S"), 
				new Beat(startTime + gap * 1023, "D"),
				new Beat(startTime + gap * 1026, "D"),
				new Beat(startTime + gap * 1027, "D"),
				new Beat(startTime + gap * 1028, "D"),
				new Beat(startTime + gap * 1029, "S"),
				new Beat(startTime + gap * 1030, "J"), 
				new Beat(startTime + gap * 1031, "F"),             
				new Beat(startTime + gap * 1032, "D"),
				new Beat(startTime + gap * 1033, "S"), 
				new Beat(startTime + gap * 1036, "S"),
				new Beat(startTime + gap * 1037, "D"),
				new Beat(startTime + gap * 1040, "S"),
				new Beat(startTime + gap * 1041, "D"),
				new Beat(startTime + gap * 1043, "S"),  
				new Beat(startTime + gap * 1044, "S"),
				new Beat(startTime + gap * 1045, "K"),
				new Beat(startTime + gap * 1046, "F"),
				new Beat(startTime + gap * 1047, "D"),
				new Beat(startTime + gap * 1048, "S"), 
				new Beat(startTime + gap * 1050, "F"),
				new Beat(startTime + gap * 1051, "D"),
				new Beat(startTime + gap * 1052, "S"),
				new Beat(startTime + gap * 1053, "D"),
				new Beat(startTime + gap * 1055, "F"), 
				new Beat(startTime + gap * 1056, "D"),
				new Beat(startTime + gap * 1057, "J"), 
				new Beat(startTime + gap * 1058, "S"), 
				new Beat(startTime + gap * 1059, "S"),
				new Beat(startTime + gap * 1060, "D"),              
				new Beat(startTime + gap * 1061, "J"),
				new Beat(startTime + gap * 1062, "K"),  
				new Beat(startTime + gap * 1063, "L"),
				new Beat(startTime + gap * 1064, "D"), 
				new Beat(startTime + gap * 1065, "K"),
				new Beat(startTime + gap * 1066, "L"), 
				new Beat(startTime + gap * 1067, "Space"), 
				new Beat(startTime + gap * 1068, "Space"),
				new Beat(startTime + gap * 1069, "Space"),
				new Beat(startTime + gap * 1070, "Space"), 
				new Beat(startTime + gap * 1071, "F"),
				new Beat(startTime + gap * 1072, "D"),
				new Beat(startTime + gap * 1073, "F"), 
				new Beat(startTime + gap * 1074, "K"), 
				new Beat(startTime + gap * 1075, "K"), 
				new Beat(startTime + gap * 1077, "D"),
				new Beat(startTime + gap * 1078, "S"),              
				new Beat(startTime + gap * 1079, "D"),
				new Beat(startTime + gap * 1080, "F"),  
				new Beat(startTime + gap * 1081, "D"), 
				new Beat(startTime + gap * 1082, "K"), 
				new Beat(startTime + gap * 1083, "J"),
				new Beat(startTime + gap * 1084, "K"), 
				new Beat(startTime + gap * 1085, "Space"),
				new Beat(startTime + gap * 1086, "J"),
				new Beat(startTime + gap * 1087, "K"),  
				new Beat(startTime + gap * 1088, "L"),
				new Beat(startTime + gap * 1089, "S"),  
				new Beat(startTime + gap * 1090, "D"),
				new Beat(startTime + gap * 1091, "F"), 
				new Beat(startTime + gap * 1095, "S"), 
				new Beat(startTime + gap * 1096, "D"),
				new Beat(startTime + gap * 1097, "D"),
				new Beat(startTime + gap * 1098, "D"),
				new Beat(startTime + gap * 1099, "D"),
				new Beat(startTime + gap * 1100, "S"),
				new Beat(startTime + gap * 1101, "J"), 
				new Beat(startTime + gap * 1102, "F"),             
				new Beat(startTime + gap * 1103, "D"),
				new Beat(startTime + gap * 1105, "S"), 
				new Beat(startTime + gap * 1106, "S"),
				new Beat(startTime + gap * 1107, "D"),
				new Beat(startTime + gap * 1108, "S"),
				new Beat(startTime + gap * 1109, "D"),
				new Beat(startTime + gap * 1110, "S"),  
				new Beat(startTime + gap * 1111, "S"),
				new Beat(startTime + gap * 1112, "K"),
				new Beat(startTime + gap * 1113, "F"),
				new Beat(startTime + gap * 1115, "D"),
				new Beat(startTime + gap * 1116, "S"), 
				new Beat(startTime + gap * 1117, "F"),
				new Beat(startTime + gap * 1118, "D"),
				new Beat(startTime + gap * 1119, "S"),
				new Beat(startTime + gap * 1120, "D"),
				new Beat(startTime + gap * 1122, "F"), 
				new Beat(startTime + gap * 1123, "D"),
				new Beat(startTime + gap * 1124, "J"), 
				new Beat(startTime + gap * 1125, "S"), 
				new Beat(startTime + gap * 1126, "S"),
				new Beat(startTime + gap * 1127, "D"),              
				new Beat(startTime + gap * 1128, "J"),
				new Beat(startTime + gap * 1129, "K"),  
				new Beat(startTime + gap * 1130, "L"),
				new Beat(startTime + gap * 1131, "D"), 
				new Beat(startTime + gap * 1133, "K"),
				new Beat(startTime + gap * 1134, "L"), 
				new Beat(startTime + gap * 1135, "Space"), 
				new Beat(startTime + gap * 1136, "Space"),
				new Beat(startTime + gap * 1137, "Space"),
				new Beat(startTime + gap * 1138, "Space"), 
				new Beat(startTime + gap * 1139, "F"),
				new Beat(startTime + gap * 1140, "D"),
				new Beat(startTime + gap * 1141, "F"), 
				new Beat(startTime + gap * 1142, "K"), 
				new Beat(startTime + gap * 1143, "K"), 
				new Beat(startTime + gap * 1144, "D"),
				new Beat(startTime + gap * 1145, "S"),              
				new Beat(startTime + gap * 1146, "D"),
				new Beat(startTime + gap * 1147, "F"),  
				new Beat(startTime + gap * 1148, "D"), 
				new Beat(startTime + gap * 1149, "K"), 
				new Beat(startTime + gap * 1150, "J"),
				new Beat(startTime + gap * 1151, "K"), 
				new Beat(startTime + gap * 1152, "Space"),
				new Beat(startTime + gap * 1153, "F"), 
				new Beat(startTime + gap * 1155, "S"), 
				new Beat(startTime + gap * 1156, "D"),
				new Beat(startTime + gap * 1158, "D"),
				new Beat(startTime + gap * 1159, "D"),
				new Beat(startTime + gap * 1160, "D"),
				new Beat(startTime + gap * 1161, "S"),
				new Beat(startTime + gap * 1162, "J"), 
				new Beat(startTime + gap * 1163, "F"),             
				new Beat(startTime + gap * 1164, "D"),
				new Beat(startTime + gap * 1165, "S"), 
				new Beat(startTime + gap * 1168, "S"),
				new Beat(startTime + gap * 1169, "D"),
				new Beat(startTime + gap * 1172, "S"),
				new Beat(startTime + gap * 1173, "D"),
				new Beat(startTime + gap * 1174, "S"),  
				new Beat(startTime + gap * 1175, "S"),
				new Beat(startTime + gap * 1176, "K"),
				new Beat(startTime + gap * 1178, "F"),
				new Beat(startTime + gap * 1179, "D"),
				new Beat(startTime + gap * 1180, "S"), 
				new Beat(startTime + gap * 1181, "F"),
				new Beat(startTime + gap * 1183, "D"),
				new Beat(startTime + gap * 1184, "S"),
				new Beat(startTime + gap * 1187, "D"),
				new Beat(startTime + gap * 1188, "F"), 
				new Beat(startTime + gap * 1189, "D"),
				new Beat(startTime + gap * 1190, "J"), 
				new Beat(startTime + gap * 1191, "S"), 
				new Beat(startTime + gap * 1192, "S"),
				new Beat(startTime + gap * 1193, "D"),              
				new Beat(startTime + gap * 1194, "J"),
				new Beat(startTime + gap * 1195, "K"),  
				new Beat(startTime + gap * 1196, "L"),
				new Beat(startTime + gap * 1197, "D"), 
				new Beat(startTime + gap * 1197, "K"),
				new Beat(startTime + gap * 1198, "L"), 
				new Beat(startTime + gap * 1199, "Space"), 
				new Beat(startTime + gap * 1200, "L"),
				new Beat(startTime + gap * 1202, "L"),  
				new Beat(startTime + gap * 1204, "K"),
				new Beat(startTime + gap * 1204, "J"),
				new Beat(startTime + gap * 1206, "D"),
				new Beat(startTime + gap * 1206, "S"),
				new Beat(startTime + gap * 1208, "Space"), 
				new Beat(startTime + gap * 1210, "D"),
				new Beat(startTime + gap * 1212, "S"),
				new Beat(startTime + gap * 1213, "D"),
				new Beat(startTime + gap * 1214, "F"),
				new Beat(startTime + gap * 1215, "F"),
				new Beat(startTime + gap * 1216, "J"),
				new Beat(startTime + gap * 1217, "L"), 
				new Beat(startTime + gap * 1218, "S"), 
				new Beat(startTime + gap * 1220, "D"),
				new Beat(startTime + gap * 1221, "F"),              
				new Beat(startTime + gap * 1222, "J"),
				new Beat(startTime + gap * 1223, "K"),  
				new Beat(startTime + gap * 1224, "L"),
				new Beat(startTime + gap * 1225, "S"),  
				new Beat(startTime + gap * 1226, "D"),
				new Beat(startTime + gap * 1228, "F"),
				new Beat(startTime + gap * 1231, "S"), 
				new Beat(startTime + gap * 1232, "D"),
				new Beat(startTime + gap * 1234, "D"),
				new Beat(startTime + gap * 1236, "D"),
				new Beat(startTime + gap * 1238, "D"),
				new Beat(startTime + gap * 1238, "S"),
				new Beat(startTime + gap * 1240, "J"), 
				new Beat(startTime + gap * 1241, "F"),             
				new Beat(startTime + gap * 1242, "D"),
				new Beat(startTime + gap * 1244, "S"), 
				new Beat(startTime + gap * 1245, "S"),
				new Beat(startTime + gap * 1246, "D"),
				new Beat(startTime + gap * 1248, "S"),
				new Beat(startTime + gap * 1250, "D"),
				new Beat(startTime + gap * 1253, "S"),  
				new Beat(startTime + gap * 1256, "S"),
				new Beat(startTime + gap * 1258, "K"),
				new Beat(startTime + gap * 1258, "F"),
				new Beat(startTime + gap * 1260, "D"),
				new Beat(startTime + gap * 1260, "S"), 
				new Beat(startTime + gap * 1261, "F"),
				new Beat(startTime + gap * 1262, "D"),
				new Beat(startTime + gap * 1263, "S"),
				new Beat(startTime + gap * 1264, "D"),
				new Beat(startTime + gap * 1266, "F"), 
				new Beat(startTime + gap * 1268, "D"),
				new Beat(startTime + gap * 1269, "J"), 
				new Beat(startTime + gap * 1270, "S"), 
				new Beat(startTime + gap * 1271, "S"),
				new Beat(startTime + gap * 1272, "D"),              
				new Beat(startTime + gap * 1274, "J"),
				new Beat(startTime + gap * 1275, "K"), 
				new Beat(startTime + gap * 1276, "D"),
				new Beat(startTime + gap * 1277, "D"),
				new Beat(startTime + gap * 1278, "S"),
				new Beat(startTime + gap * 1279, "J"), 
				new Beat(startTime + gap * 1280, "F"),             
				new Beat(startTime + gap * 1282, "D"),
				new Beat(startTime + gap * 1282, "S"), 
				new Beat(startTime + gap * 1283, "S"),
				new Beat(startTime + gap * 1285, "D"),
				new Beat(startTime + gap * 1286, "S"),
				new Beat(startTime + gap * 1287, "D"),
				new Beat(startTime + gap * 1288, "S"),  
				new Beat(startTime + gap * 1289, "S"),
				new Beat(startTime + gap * 1290, "K"),
				new Beat(startTime + gap * 1291, "F"),
				new Beat(startTime + gap * 1292, "D"),
				new Beat(startTime + gap * 1293, "S"), 
				new Beat(startTime + gap * 1294, "F"),
				new Beat(startTime + gap * 1295, "D"),
				new Beat(startTime + gap * 1296, "S"),
				new Beat(startTime + gap * 1297, "D"),
				new Beat(startTime + gap * 1298, "F"), 
				new Beat(startTime + gap * 1298, "D"),
				new Beat(startTime + gap * 1298, "J"), 
				new Beat(startTime + gap * 1299, "S"), 
				new Beat(startTime + gap * 1300, "S"),
				new Beat(startTime + gap * 1302, "D"),              
				new Beat(startTime + gap * 1303, "J"),
				new Beat(startTime + gap * 1304, "K"),  
				new Beat(startTime + gap * 1305, "L"),
				new Beat(startTime + gap * 1306, "D"), 
				new Beat(startTime + gap * 1307, "K"),
				new Beat(startTime + gap * 1308, "L"), 
				new Beat(startTime + gap * 1310, "Space"), 
				new Beat(startTime + gap * 1311, "D"), 
				new Beat(startTime + gap * 1312, "K"),
				new Beat(startTime + gap * 1313, "L"), 
				new Beat(startTime + gap * 1314, "Space"),
				new Beat(startTime + gap * 1315, "Space"),
				new Beat(startTime + gap * 1316, "Space"),
				new Beat(startTime + gap * 1317, "Space"),
				new Beat(startTime + gap * 1318, "S"), 
				new Beat(startTime + gap * 1318, "F"),
				new Beat(startTime + gap * 1320, "D"),
				new Beat(startTime + gap * 1320, "S"),
				new Beat(startTime + gap * 1322, "D"),
				new Beat(startTime + gap * 1323, "F"), 
				new Beat(startTime + gap * 1324, "D"),
				new Beat(startTime + gap * 1325, "J"), 
				new Beat(startTime + gap * 1326, "S"), 
				new Beat(startTime + gap * 1328, "S"),
				new Beat(startTime + gap * 1329, "D"),              
				new Beat(startTime + gap * 1330, "J"),
				new Beat(startTime + gap * 1331, "K"),  
				new Beat(startTime + gap * 1332, "L"),
				new Beat(startTime + gap * 1333, "D"), 
				new Beat(startTime + gap * 1336, "K"),
				new Beat(startTime + gap * 1336, "L"), 
				new Beat(startTime + gap * 1338, "Space"), 
				new Beat(startTime + gap * 1340, "L"),
				new Beat(startTime + gap * 1341, "L"),  
				new Beat(startTime + gap * 1342, "K"),
				new Beat(startTime + gap * 1343, "J"),
				new Beat(startTime + gap * 1344, "D"),
				new Beat(startTime + gap * 1345, "S"),
				new Beat(startTime + gap * 1346, "Space"), 
				new Beat(startTime + gap * 1347, "D"),
				new Beat(startTime + gap * 1349, "S"),
				new Beat(startTime + gap * 1350, "D"),
				new Beat(startTime + gap * 1351, "L"), 
				new Beat(startTime + gap * 1353, "Space"), 
				new Beat(startTime + gap * 1354, "Space"),
				new Beat(startTime + gap * 1355, "Space"),
				new Beat(startTime + gap * 1356, "Space"), 
				new Beat(startTime + gap * 1357, "F"),
				new Beat(startTime + gap * 1358, "D"),
				new Beat(startTime + gap * 1359, "F"), 
				new Beat(startTime + gap * 1360, "K"), 
				new Beat(startTime + gap * 1362, "D"),
				new Beat(startTime + gap * 1363, "S"),              
				new Beat(startTime + gap * 1364, "D"),
				new Beat(startTime + gap * 1365, "F"),  
				new Beat(startTime + gap * 1366, "D"), 
				new Beat(startTime + gap * 1368, "K"), 
				new Beat(startTime + gap * 1369, "J"),
				new Beat(startTime + gap * 1370, "K"), 
				new Beat(startTime + gap * 1372, "Space"),
				new Beat(startTime + gap * 1373, "Space"),
				new Beat(startTime + gap * 1375, "L"),
				new Beat(startTime + gap * 1376, "D"),
				new Beat(startTime + gap * 1378, "F"),
				new Beat(startTime + gap * 1379, "F"),
				new Beat(startTime + gap * 1380, "F"), 
				new Beat(startTime + gap * 1382, "S"), 
				new Beat(startTime + gap * 1384, "D"),
				new Beat(startTime + gap * 1385, "F"),             
				new Beat(startTime + gap * 1386, "D"),
				new Beat(startTime + gap * 1387, "S"), 
				new Beat(startTime + gap * 1389, "F"),
				new Beat(startTime + gap * 1389, "K"),
				new Beat(startTime + gap * 1390, "L"),
				new Beat(startTime + gap * 1392, "L"),
				new Beat(startTime + gap * 1395, "L"),
				new Beat(startTime + gap * 1397, "K"),
				new Beat(startTime + gap * 1399, "J"),
				new Beat(startTime + gap * 1400, "D"),
				new Beat(startTime + gap * 1405, "S"),
				new Beat(startTime + gap * 1407, "Space"), 
				new Beat(startTime + gap * 1408, "D"),
				new Beat(startTime + gap * 1409, "S"),
				new Beat(startTime + gap * 1410, "D"),
				new Beat(startTime + gap * 1411, "F"),
				new Beat(startTime + gap * 1412, "F"),
				new Beat(startTime + gap * 1414, "J"),
				new Beat(startTime + gap * 1415, "L"), 
				new Beat(startTime + gap * 1416, "S"), 
				new Beat(startTime + gap * 1417, "D"),
				new Beat(startTime + gap * 1418, "F"),              
				new Beat(startTime + gap * 1419, "J"),
				new Beat(startTime + gap * 1420, "K"),  
				new Beat(startTime + gap * 1423, "L"),
				new Beat(startTime + gap * 1426, "S"),  
				new Beat(startTime + gap * 1428, "D"),
				new Beat(startTime + gap * 1430, "F"), 
				new Beat(startTime + gap * 1431, "S"), 
				new Beat(startTime + gap * 1433, "D"),
				new Beat(startTime + gap * 1435, "D"),
				new Beat(startTime + gap * 1436, "D"),
				new Beat(startTime + gap * 1437, "D"),
				new Beat(startTime + gap * 1438, "S"),
				new Beat(startTime + gap * 1439, "D"),
				new Beat(startTime + gap * 1440, "S"),
				new Beat(startTime + gap * 1442, "Space"), 
				new Beat(startTime + gap * 1444, "D"),
				new Beat(startTime + gap * 1446, "S"),
				new Beat(startTime + gap * 1446, "D"),
				new Beat(startTime + gap * 1449, "F"),
				new Beat(startTime + gap * 1451, "F"),
				new Beat(startTime + gap * 1452, "J"),
				new Beat(startTime + gap * 1454, "L"), 
				new Beat(startTime + gap * 1455, "S"), 
				new Beat(startTime + gap * 1456, "D"),
				new Beat(startTime + gap * 1457, "F"),              
				new Beat(startTime + gap * 1458, "J"),
				new Beat(startTime + gap * 1459, "K"),  
				new Beat(startTime + gap * 1460, "L"),
				new Beat(startTime + gap * 1461, "S"),  
				new Beat(startTime + gap * 1462, "D"),
				new Beat(startTime + gap * 1463, "F"), 
				new Beat(startTime + gap * 1464, "S"), 
				new Beat(startTime + gap * 1465, "D"),
				new Beat(startTime + gap * 1466, "D"),
				new Beat(startTime + gap * 1467, "D"),
				new Beat(startTime + gap * 1468, "D"),
				new Beat(startTime + gap * 1469, "S"),
				new Beat(startTime + gap * 1470, "D"),
				new Beat(startTime + gap * 1472, "D"),
				new Beat(startTime + gap * 1474, "D"),
				new Beat(startTime + gap * 1475, "S"),
				new Beat(startTime + gap * 1477, "D"),
				new Beat(startTime + gap * 1478, "S"),
				new Beat(startTime + gap * 1480, "Space"), 
				new Beat(startTime + gap * 1482, "D"),
				new Beat(startTime + gap * 1482, "S"),
				new Beat(startTime + gap * 1483, "D"),
				new Beat(startTime + gap * 1484, "F"),
				new Beat(startTime + gap * 1485, "F"),
				new Beat(startTime + gap * 1487, "J"),
				new Beat(startTime + gap * 1488, "L"), 
				new Beat(startTime + gap * 1489, "S"), 
				new Beat(startTime + gap * 1490, "D"),
				new Beat(startTime + gap * 1491, "F"),              
				new Beat(startTime + gap * 1492, "J"),
				new Beat(startTime + gap * 1493, "K"),  
				new Beat(startTime + gap * 1495, "L"),
				new Beat(startTime + gap * 1497, "S"),  
				new Beat(startTime + gap * 1498, "D"),
				new Beat(startTime + gap * 1500, "F"), 
				new Beat(startTime + gap * 1502, "S"), 
				new Beat(startTime + gap * 1503, "D"),
				new Beat(startTime + gap * 1504, "D"),
				new Beat(startTime + gap * 1505, "D"),
				new Beat(startTime + gap * 1507, "D"),
				new Beat(startTime + gap * 1508, "S"),
				new Beat(startTime + gap * 1509, "F"),              
				new Beat(startTime + gap * 1510, "J"),
				new Beat(startTime + gap * 1511, "K"),  
				new Beat(startTime + gap * 1512, "L"),
				new Beat(startTime + gap * 1513, "S"),  
				new Beat(startTime + gap * 1514, "D"),
				new Beat(startTime + gap * 1515, "F"), 
				new Beat(startTime + gap * 1517, "S"), 
				new Beat(startTime + gap * 1517, "D"),
				new Beat(startTime + gap * 1519, "D"),
				new Beat(startTime + gap * 1521, "D"),
				new Beat(startTime + gap * 1522, "D"),
				new Beat(startTime + gap * 1523, "S"),
				new Beat(startTime + gap * 1523, "J"), 
				new Beat(startTime + gap * 1525, "F"),             
				new Beat(startTime + gap * 1526, "D"),
				new Beat(startTime + gap * 1527, "S"), 
				new Beat(startTime + gap * 1528, "S"),
				new Beat(startTime + gap * 1530, "D"),
				new Beat(startTime + gap * 1531, "S"),
				new Beat(startTime + gap * 1532, "D"),
				new Beat(startTime + gap * 1533, "S"),  
				new Beat(startTime + gap * 1534, "S"),
				new Beat(startTime + gap * 1535, "K"),
				new Beat(startTime + gap * 1537, "F"),
				new Beat(startTime + gap * 1538, "D"),
				new Beat(startTime + gap * 1539, "S"), 
				new Beat(startTime + gap * 1540, "F"),
				new Beat(startTime + gap * 1541, "D"),
				new Beat(startTime + gap * 1543, "S"),
				new Beat(startTime + gap * 1545, "D"),
				new Beat(startTime + gap * 1547, "F"), 
				new Beat(startTime + gap * 1548, "D"),
				new Beat(startTime + gap * 1549, "J"), 
				new Beat(startTime + gap * 1551, "S"), 
				new Beat(startTime + gap * 1552, "S"),
				new Beat(startTime + gap * 1553, "D"),              
				new Beat(startTime + gap * 1555, "J"),
				new Beat(startTime + gap * 1556, "K"),  
				new Beat(startTime + gap * 1557, "L"),
				new Beat(startTime + gap * 1558, "D"), 
				new Beat(startTime + gap * 1559, "K"),
				new Beat(startTime + gap * 1560, "L"), 
				new Beat(startTime + gap * 1561, "Space"), 
				new Beat(startTime + gap * 1562, "Space"),
				new Beat(startTime + gap * 1563, "Space"),
				new Beat(startTime + gap * 1563, "J"), 
				new Beat(startTime + gap * 1564, "F"),
				new Beat(startTime + gap * 1566, "D"),
				new Beat(startTime + gap * 1568, "F"), 
				new Beat(startTime + gap * 1570, "K"), 
				new Beat(startTime + gap * 1572, "K"), 
				new Beat(startTime + gap * 1573, "D"),
				new Beat(startTime + gap * 1574, "S"),              
				new Beat(startTime + gap * 1575, "D"),
				new Beat(startTime + gap * 1577, "F"),  
				new Beat(startTime + gap * 1578, "D"), 
				new Beat(startTime + gap * 1582, "K"), 
				new Beat(startTime + gap * 1584, "J"),
				new Beat(startTime + gap * 1586, "K"), 
				new Beat(startTime + gap * 1587, "Space"),
				new Beat(startTime + gap * 1589, "Space"),
				new Beat(startTime + gap * 1591, "L"),
				new Beat(startTime + gap * 1593, "D"),
				new Beat(startTime + gap * 1595, "F"),
				new Beat(startTime + gap * 1597, "F"),
				new Beat(startTime + gap * 1598, "F"), 
				new Beat(startTime + gap * 1599, "S"), 
				new Beat(startTime + gap * 1600, "D"),
				new Beat(startTime + gap * 1601, "F"),             
				new Beat(startTime + gap * 1603, "D"),
				new Beat(startTime + gap * 1605, "D"),
				new Beat(startTime + gap * 1606, "J"), 
				new Beat(startTime + gap * 1608, "S"), 
				new Beat(startTime + gap * 1610, "S"),
				new Beat(startTime + gap * 1612, "D"),              
				new Beat(startTime + gap * 1614, "J"),
				new Beat(startTime + gap * 1616, "K"),  
				new Beat(startTime + gap * 1618, "L"),
				new Beat(startTime + gap * 1620, "D"), 
				new Beat(startTime + gap * 1621, "K"),
				new Beat(startTime + gap * 1623, "L"), 
				new Beat(startTime + gap * 1625, "Space"), 
				new Beat(startTime + gap * 1627, "Space"),
				new Beat(startTime + gap * 1628, "Space"),
				new Beat(startTime + gap * 1630, "Space"), 
				new Beat(startTime + gap * 1632, "F"),
				new Beat(startTime + gap * 1634, "D"),
				new Beat(startTime + gap * 1635, "F"), 
				new Beat(startTime + gap * 1638, "K"), 
				new Beat(startTime + gap * 1639, "K"), 
				new Beat(startTime + gap * 1641, "D"),
				new Beat(startTime + gap * 1643, "S"),              
				new Beat(startTime + gap * 1645, "D"),
				new Beat(startTime + gap * 1647, "F"),  
				new Beat(startTime + gap * 1648, "D"), 
				new Beat(startTime + gap * 1649, "K"), 
				new Beat(startTime + gap * 1649, "J"),
				new Beat(startTime + gap * 1651, "K"), 
				new Beat(startTime + gap * 1652, "Space"),
				new Beat(startTime + gap * 1653, "Space"),
				new Beat(startTime + gap * 1655, "L"),
				new Beat(startTime + gap * 1656, "D"),
				new Beat(startTime + gap * 1657, "F"),
				new Beat(startTime + gap * 1658, "F"),
				new Beat(startTime + gap * 1659, "F"), 
				new Beat(startTime + gap * 1661, "S"), 
				new Beat(startTime + gap * 1663, "D"),
				new Beat(startTime + gap * 1665, "F"),
				new Beat(startTime + gap * 1591, "L"),
				new Beat(startTime + gap * 1593, "D"),
				new Beat(startTime + gap * 1595, "F"),
				new Beat(startTime + gap * 1597, "F"),
				new Beat(startTime + gap * 1598, "F"), 
				new Beat(startTime + gap * 1599, "S"), 
				new Beat(startTime + gap * 1600, "D"),
				new Beat(startTime + gap * 1601, "F"),             
				new Beat(startTime + gap * 1603, "D"),
				new Beat(startTime + gap * 1605, "D"),
				new Beat(startTime + gap * 1606, "J"), 
				new Beat(startTime + gap * 1608, "S"), 
				new Beat(startTime + gap * 1610, "S"),
				new Beat(startTime + gap * 1612, "D"),              
				new Beat(startTime + gap * 1614, "J"),
				new Beat(startTime + gap * 1616, "K"),  
				new Beat(startTime + gap * 1618, "L"),
				new Beat(startTime + gap * 1620, "D"), 
				new Beat(startTime + gap * 1621, "K"),
				new Beat(startTime + gap * 1623, "L"), 
				new Beat(startTime + gap * 1492, "J"),
				new Beat(startTime + gap * 1493, "K"),  
				new Beat(startTime + gap * 1495, "L"),
				new Beat(startTime + gap * 1497, "S"),  
				new Beat(startTime + gap * 1498, "D"),
				new Beat(startTime + gap * 1500, "F"), 
				new Beat(startTime + gap * 1502, "S"), 
				new Beat(startTime + gap * 1503, "D"),
				new Beat(startTime + gap * 1504, "D"),
				new Beat(startTime + gap * 1505, "D"),
				new Beat(startTime + gap * 1507, "D"),
				new Beat(startTime + gap * 1508, "S"),
				new Beat(startTime + gap * 1509, "F"),              
				new Beat(startTime + gap * 1510, "J"),
				new Beat(startTime + gap * 1511, "K"),  
				new Beat(startTime + gap * 1512, "L"),
				new Beat(startTime + gap * 1513, "S"),  
				new Beat(startTime + gap * 1514, "D"),
				new Beat(startTime + gap * 1515, "F"), 
				new Beat(startTime + gap * 1517, "S"), 
				new Beat(startTime + gap * 1517, "D"),
				new Beat(startTime + gap * 1519, "D"),
				new Beat(startTime + gap * 1521, "D"),
				new Beat(startTime + gap * 1522, "D"),
				new Beat(startTime + gap * 1523, "S"),
				//this was hell. I should have invested in a converter
				//and a simfile reader
		};
	}
	
	@Override
	public void update() {
		
		
		for (int i = 0; i < notes.size(); i++) {
			Note note = notes.get(i);
			note.update();
			if(note.isProceeded() == false ) {
				notes.remove(i);
				i--;
			}
		}
		
		
		effect.update();
		
		if(displayResult) {
			if(!showingResult) {
				showingResult = true;
				rbg.playBgm();
				rbg.takeMusicTitle("Shiawase no Monosashi - Mariya ");
				rbg.takeScore(score);
				rbg.writeScore();
				rbg.calRank();
			}
			rbg.update();
		}
		
	}

	@Override
	public void draw(Graphics2D g) {
		
		bg.draw(g);
		
		g.setColor(Color.WHITE);
		g.setRenderingHint(
				RenderingHints.KEY_TEXT_ANTIALIASING,
				RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
		g.setFont(new Font("Elephant", Font.BOLD, 26));
		g.drawString("Shiawase no Monosashi - Mariya", 10, 694);
		
		g.setColor(Color.LIGHT_GRAY);
		g.setFont(new Font("Elephant", Font.BOLD, 26));
		g.drawString(String.valueOf(score), 636, 694);
		g.drawString("Hard", 1140, 694);
		
		for (int i = 0; i < notes.size(); i++) {
			Note note = notes.get(i);
			note.draw(g);
		}
		
		effect.draw(g);
		
		if(displayResult) {
			rbg.draw(g);
		}
		
	}

	@Override
	public void keyPressed(int k) {
		
		if(k == KeyEvent.VK_ESCAPE) {
			
			exit = true;
			
		
			gameMusic.close();
			rbg.closeBgm();
			
			for (int i = 0; i < notes.size(); i++) {
				Note note = notes.get(i);
				note.setProceeded(false);
			}
			game.interrupt();
			
			gsm.setStateInit(GameStateManager.MENUSTATE);
			gsm.setState(GameStateManager.MENUSTATE); 
			
		}
		
		if(!displayResult) {
			
			beatSound = new Music("beat.mp3", false);
			beatSound.start();
			
			if (k == KeyEvent.VK_S) {
				judge("S");
				bg.pressS();
			} 
			else if (k == KeyEvent.VK_D) {
				judge("D");
				bg.pressD();
			} 
			else if (k == KeyEvent.VK_F) {
				judge("F");
				bg.pressF();
			} 
			else if (k == KeyEvent.VK_SPACE) {
				judge("Space");
				bg.pressSpace();
			} 
			else if (k == KeyEvent.VK_J) {
				judge("J");
				bg.pressJ();
			} 
			else if (k == KeyEvent.VK_K) {
				judge("K");
				bg.pressK();
			} 
			else if (k == KeyEvent.VK_L) {
				judge("L");
				bg.pressL();
			}
		}
		
		else if(displayResult) {
			if(k == KeyEvent.VK_ENTER && rbg.getNextGame()) {
				gsm.setStateInit(GameStateManager.MENUSTATE);
				gsm.setState(GameStateManager.MENUSTATE); 
			}
			
		}
		
	}

	@Override
	public void keyReleased(int k) {
		if (k == KeyEvent.VK_S) bg.releaseS();
		else if (k == KeyEvent.VK_D) bg.releaseD();
		else if (k == KeyEvent.VK_F) bg.releaseF();
		else if (k == KeyEvent.VK_SPACE) bg.releaseSpace();
		else if (k == KeyEvent.VK_J) bg.releaseJ();
		else if (k == KeyEvent.VK_K) bg.releaseK();
		else if (k == KeyEvent.VK_L) bg.releaseL();
	}

	public void judge(String input)
	{
		for (int i = 0; i < notes.size(); i++) {
			Note note = notes.get(i);
			if(input.equals(note.getNoteType()))
			{
				if (note.judge().equals("Miss")) {
					effect.setCombo("Miss", 0); 
					effect.setPosition(note.getNoteType());
					effect.setEffect(); 
					combo = 0;
				}
				if (note.judge().equals("Perfect")){
					effect.setCombo("Perfect", combo); 
					effect.setPosition(note.getNoteType());
					effect.setEffect(); 
					combo++;
					score += 100 + combo * 5;
				}
				if (note.judge().equals("Great")){
					effect.setCombo("Great", combo); 
					effect.setPosition(note.getNoteType());
					effect.setEffect(); 
					combo++;
					score += 80 + combo * 5;
				}
				if (note.judge().equals("Good")){
					effect.setCombo("Good", combo); 
					effect.setPosition(note.getNoteType());
					effect.setEffect(); 
					combo++;
					score += 60 + combo * 5;
				}
				break;
			}
		}
	}
	
	
	@Override
	public void run() {
		
		int i =0;

			while (i < beats.length && !game.isInterrupted()) {

				if (beats[i].getTime() <= gameMusic.getTime()) {
					Note note = new Note(beats[i].getNoteName());
					notes.add(note);
					i++;
				}
			}
			
		if (!exit) {
			try {
				Thread.sleep(5000);
			} catch (Exception e) {e.printStackTrace();}
			rbg.calRank();
			displayResult = true;
		}

	}
	

}
